version: '3.7'
services:
  postgres:
    container_name: postgres-clean-heroes
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clean-heroes
    ports:
      - "5432:5432"